# Generated by Django 6.0.6 on 2026-09-09 01:18

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_author_book_author_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Use a 1-10 scale, in steps of 0.5",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1")),
                    django.core.validators.MaxValueValidator(Decimal("10")),
                ],
            ),
        ),
    ]
